router_id: 10.250.0.6
interfaces:
    - name: "ge-0/0/0"
      description: "To AGG-01"
      ip_address: "10.255.3.6"
      subnet_mask: "30"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.3"        
    - name: "ge-0/0/1"
      description: "To SRT-Q09"
      ip_address: "10.255.3.13"
      subnet_mask: "30"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.3"
    - name: "lo0"
      description: "Loopback"
      ip_address: "10.250.0.6"
      subnet_mask: "32"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.3"     
hostname: SRT-Q07        