router_id: 10.250.0.5
interfaces:
    - name: "ge-0/0/0"
      description: "To AGG-01"
      ip_address: "10.255.2.6"
      subnet_mask: "30"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.2"        
    - name: "ge-0/0/1"
      description: "To AGG-02"
      ip_address: "10.255.2.10"
      subnet_mask: "30"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.2"
    - name: "lo0"
      description: "Loopback"
      ip_address: "10.250.0.5"
      subnet_mask: "32"
      unit: 0
      family:
        - inet
        - mpls
      ospf:
        area: "0.0.0.2"    
hostname: SRT-Q01        